### ISSUE TITLE
missing browse server button

### ISSUE THREAD

**Issue by motox1992** [anguskwalker/inserthtmlfile#1]
hello,
i'd like to use this plugin but when i install it the browse server button is hidden with inline style display none. my ckeditor build has the prebuilt file manager but your plugin doesn't seem to be hooking up to it. is there something else i need to do to get that to work? sorry i'm new to ckeditor so i don't know how to solve this or what info you might need to know to help me fix this.  thanks for your help

**Comment by anguskwalker** [comment]
Hi There,
Sorry for the delayed response.
There are many ways to configure your toolbars. 
This page should help you. 
[https://docs.ckeditor.com/ckeditor4/latest/guide/dev_toolbar.html](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_toolbar.html)
remember, the button name is: inserthtmlfile

**Comment by anguskwalker** [comment]
No further comment so assuming resolved
